课堂演示数据下载

1. 创建NDArray数组：

    1. 从列表生成数组

        numpy.arrar(列表)
        如果列表中有多种类型，则会执行强制转换。转换遵循向上兼容原则：整数->浮点数->str等各类对象

    2. 用函数生成规律性数组

        numpy.zeros
        numpy.ones
        numpy.eye
        numpy.arange

    3. 用函数生成随机数组

        numpy.random.rand
        numpy.random.randint
        numpy.random.choice
        ......

2. list列表的元素类型可以混合多种类型，但是NDArray要求所有的元素类型完全一致。如果把一个同时包含数字与字符串两种类型元素的list列表转换为NDArray时，将通过强制转换，确保类型全部统一：list列表中的数字将转换为NDArray中的数字字符串，而字符串类型的元素保持不变。

3. dtype指列表转换为NDArray之后每个元素的类型，字母“U”代表unicode字符类型，“11”表示每个元素所占的空间长度。

4. 对形状长度不一致的列表不推荐进行转换操作，并且即将不被允许，因为在NDArray中二维数组必须是整齐满行满列的，不能有缺失值。例如以下的转换将引发警告：

    x = [[1, 2], [1, 2, 3]]
    a = np.array(x)
5. numpy.zeros函数生成全部是0的数组：

    1. 生成一维数组
        a = np.zeros(10)
    2. 通过dtype参数指定元素类型：
        a = np.zeros(10, dtype='int')
    3. 生成二维数组
        a = np.zeros((3, 4), dtype='int')
    4. 生成n维数组
        a = np.zeros((3, 4, 5, ... ), dtype='int')
6. numpy.ones函数生成全部是1的数组，用法同numpy.zeros：

    a = np.ones(10)
    a = np.ones((3, 4, ...), dtype='int'
7. numpy.eye函数生成对角线为1，其他位置为0的矩阵（单位矩阵）：

    a = np.eye(4, dtype='int')
8. numpy.arange函数生成指定范围的等差数组，类似range函数：

    1. 生成一维数组
        a = np.arange(1, 5)
        # array([1, 2, 3, 4])
    2. 指定步长
        a = np.arange(-5, 10, 3)
        # array([-5, -2, 1, 4, 7])
    3. 与range不同，可以使用小数步长
        a = np.arange(10, -5, -0.3)
        # array([10. , 9.7, 9.4, 9.1, ...])
9. numpy.random.rand函数生成 0~1 之间随机小数数组：

    1. 生成随机的一维数组
        a = np.random.rand(3)
    2. 生成随机的二维数组
        a = np.random.rand(3, 5)
    3. 生成随机的n维数组
        a = np.random.rand(3, 5, 5, ...)
10. numpy.random.randint函数生成随机整数数组：

       生成 -10~10 之间随机整数，共3行5列
       a = np.random.randint(-10, 11, (3, 5))
11. numpy.random.choice函数生成随机抽取的元素组成的数组：

       从列表中随机抽取元素作为数组的元素，共3行4列
       a = np.random.choice(['A', 'B', 'C'], (3, 4))
12. numpy.random.randn函数生成正态分布的随机数组；unmpy.random.uniform函数生成均匀分布的随机数组

13. numpy.loadtxt(文件路径,  分隔符, 类型)函数将文本文件读入数组，读入的数字默认视作浮点数，可以通过dtype参数指定类型：

    # 读取txt文件中以逗号分隔的整数
    a = np.loadtxt('d/course/data/销量.txt', delimiter=',', dtype='int')
需要注意的是如果文件中存在缺失值会导致读取失败。

14. numpy.genfromtxt(文件路径, 分隔符, 类型, 填充值)函数将文本文件读入数组，如果文件中存在缺失值则使用填充值进行填充：

    # 读取文件，缺失值以0填充
    a = np.genfromtxt('d/course/data/销量.txt', delimiter=',', dtype='int', filling_values=0)

In [25]:
#练习题1 请将以下列表创建为NDArray数组
import numpy as np
li = ['1', 3, 5, 7, 9, 11, 13, 17]
date=np.array(li)
li

['1', 3, 5, 7, 9, 11, 13, 17]

In [26]:
# 练习题2  请将以下列表创建为NDArray数组，元素是整数类型
li = [1, 3, 5, 7, 9, 11, 13, 17]
date=np.array(li ,dtype=int)
li

[1, 3, 5, 7, 9, 11, 13, 17]

In [27]:
#练习题3 请首先生成一个 1~100 随机数的4行4列的二维列表，再生成NDArray数组
import random
kong=[]
for x in range(4):
    linshi=[]
    for i in range(5):
        linshi.append(random.randint(0,101))
    kong.append(linshi)
kong=np.array(kong)
kong

array([[ 85,  65,  44,  99,  60],
       [100,  27,   9, 100,  59],
       [ 23,  61,  79,  98,  26],
       [ 35,  11,   6,   4,  56]])

In [28]:
#练习4
#请使用numpy创建一维随机整数数组，范围 -100 ~ 50，共100个元素。
#请使用numpy创建一维等差整数数组，范围 -50 ~ 100，步长2。
# 请使用numpy创建一维等差数组，范围 -10 ~ 10，步长0.5
arr1 = np.random.randint(-100, 51, 100)
arr2 = np.arange(-50, 102, 2)
arr3 = np.arange(-10, 10.5, 0.5)
arr1, arr2, arr3

(array([ 17,  16, -94, -86, -68, -17, -99, -13, -26,  10,  -8, -36, -35,
        -29, -10,   0, -40,  46,  38, -21,  38, -99, -34, -30, -23,  23,
        -29, -91, -89,  37, -75,  40,  17,  11, -91, -67, -61,  50, -36,
        -43, -40,  39, -91, -95, -75, -47, -80, -76,  10, -13,  47, -97,
        -99, -77, -41,  40, -48, -73, -78,   7, -57,  27,  50,  -9,  -2,
        -72, -87, -11,  14, -29, -51,  33, -65, -84, -72, -65, -74, -23,
        -84,  20, -77, -46, -14,  33,  10, -79, -12,  36, -11, -84, -77,
        -82, -11, -75,  16, -20,  49, -98,  29, -82]),
 array([-50, -48, -46, -44, -42, -40, -38, -36, -34, -32, -30, -28, -26,
        -24, -22, -20, -18, -16, -14, -12, -10,  -8,  -6,  -4,  -2,   0,
          2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
         28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
         54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
         80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100]),
 arr

In [31]:
    # 请使用numpy创建随机二维整数数组，共3行4列，范围 -50 ~ 100。
    #
    # 请使用numpy创建随机二维数组，共4行4列，元素来自于以下数据：
    #
    #     1, 'a', 2, 3, 'c', 4, 'X'
import numpy as np

arr1 = np.random.randint(-50, 101, (3, 4))
arr2 = np.random.choice([1, 'a', 2, 3, 'c', 4, 'X'], (4, 4))
arr1, arr2