1. 描述性统计是指使用一个或多个简单的数值描绘出成千上万数据整体的特征，例如最大值、最小值、平均数、总和、方差、标准差等等。

2. numpy中为描述性统计提供了统计函数（聚集函数），包括：

    max     最大值
    min     最小值
    sum     总和
    mean    平均数（算数）
    average 平均数（算数或加权）
    std     标准差
    median  中位数
    ptp     极差（最大值减最小值）
    var     样本方差
    percentile  百分位数
3. 当需要求某项特征值时，直接使用相应的聚集函数对数组进行计算即可，例如使用 sum 函数求数组元素总和：

    score = np.array([70, 80, 96])
    np.sum(score)
4. 权重表示该数据对于整体数据重要性的比重值，例如有平时、期中、期末三个成绩，平时成绩重要性占20%，期中成绩占30%，期末成绩占50%，那么这三个分数对应的权重为：20、30、50。

5. average函数使用weights参数设置权重对数组进行平均数计算，例如设置三个分数的权重分别为：20、30、50 求平均分：

    score = np.array([70, 80, 96])
    np.average(score, weights = [20, 30, 50])
加权平均分计算公式为：（70 * 20 + 80 * 30 + 96 * 50) / (20 + 30 + 50)
6. 部分聚集函数除了使用“numpy.函数名()”方式调用之外，也支持使用“数组.方法名()”方式来调用，例如：

    np.sum(score)
    # 等价于
    score.sum()
7. 请注意并不是所有的聚集函数都支持对象调用的方式，例如average函数就不支持对象方法形式的调用。

8. 对于数据集中的某一个元素，我们必须同时指明n个特征才能精确地表述出来，那么两个特征就表示这是一个n维的数据集（n维数组）。例如：

    1. 对于学生成绩来说，其中一个维度称为“姓名”，从上到下每一行属于一个单独的姓名；另一个维度称为“考试成绩类型”，从左到右每一列属于一个单独的成绩类型。

    2. 对于学成成绩来说，其中一个维度称为“科目”，每一个单独的科目中又包含两个其他维度；另外两个维度是“姓名”和“成绩类型”。

9. 数据集可能包含更多的特征（维度），例如年份、学区、家庭成员等等，超过三维之后无法再对应到坐标系或现实空间中。如果将维度理解为特征，放弃使用图形空间来表述，那么表示高纬度的数据集将变得清晰简单。

10. 在Python中使用方括号“[]”表示高纬度数，遵循以下原则：

    1. 同一个数据集里的所有内容最终一定涵盖在一对方括号里面。

    2. 一层方括号就代表有一个维度。

维度就是特征，从左到右依次编号：0、1、2 。。。

11. 常用的统计函数中都支持 axis 维度参数，使用 axis 参数设置统计维度，可以针对不同的维度进行统计计算，例如在二维数组中分别对第1号维度、第0号维度求和：

    np.sum(sh, axis=1)
    np.sum(sh, axis=0)
    # 等价于
    sh.sum(axis=1)
    sh.sum(axis=0)
统计计算的结果中对编号1的维度进行合并，数据集从二维降至一维。同理，当 axis 值为0时，对编号0的维度进行合并。

In [19]:
import numpy as np
import pprint
dt1=np.random.randint(1,10,size=(4,6))
pprint.pprint(dt1)

dt2=np.random.randint(1,10,size=(2,4,6))
pprint.pprint(dt2)
dt1/dt2

array([[7, 9, 6, 5, 9, 4],
       [4, 9, 7, 6, 6, 2],
       [3, 5, 2, 2, 2, 7],
       [3, 5, 5, 8, 7, 1]])
array([[[2, 9, 8, 4, 5, 2],
        [1, 8, 1, 5, 5, 8],
        [1, 5, 5, 4, 8, 5],
        [5, 5, 6, 7, 4, 4]],

       [[8, 8, 7, 4, 1, 8],
        [5, 2, 6, 2, 6, 9],
        [5, 2, 2, 2, 8, 6],
        [8, 3, 9, 3, 2, 1]]])


array([[[3.5       , 1.        , 0.75      , 1.25      , 1.8       ,
         2.        ],
        [4.        , 1.125     , 7.        , 1.2       , 1.2       ,
         0.25      ],
        [3.        , 1.        , 0.4       , 0.5       , 0.25      ,
         1.4       ],
        [0.6       , 1.        , 0.83333333, 1.14285714, 1.75      ,
         0.25      ]],

       [[0.875     , 1.125     , 0.85714286, 1.25      , 9.        ,
         0.5       ],
        [0.8       , 4.5       , 1.16666667, 3.        , 1.        ,
         0.22222222],
        [0.6       , 2.5       , 1.        , 1.        , 0.25      ,
         1.16666667],
        [0.375     , 1.66666667, 0.55555556, 2.66666667, 3.5       ,
         1.        ]]])